"""add room and available_seats

Revision ID: 2f179ac86460
Revises: 0226a513df21
Create Date: 2026-08-21 20:31:22.109286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f179ac86460'
down_revision: Union[str, Sequence[str], None] = '0226a513df21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('room', sa.String(), nullable=True))
    op.add_column('sections', sa.Column('available_seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'available_seats')
    op.drop_column('meetings', 'room')
    # ### end Alembic commands ###
